// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPTC3A9JRkVwFwe1RcwOOS5300tvWflL4',
    appId: '1:456863814558:web:1b7883ddeb2c40f742fc8f',
    messagingSenderId: '456863814558',
    projectId: 'todo-3494f',
    authDomain: 'todo-3494f.firebaseapp.com',
    storageBucket: 'todo-3494f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBaaA4TsZbDkJGyoRwxg1sJmQNhRoElfA',
    appId: '1:456863814558:android:5bd5391b7f883dd742fc8f',
    messagingSenderId: '456863814558',
    projectId: 'todo-3494f',
    storageBucket: 'todo-3494f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_b2J1XCwWt6vZ-FQSEbIDQqZ0pDVIKBo',
    appId: '1:456863814558:ios:3426bed7d0f7880f42fc8f',
    messagingSenderId: '456863814558',
    projectId: 'todo-3494f',
    storageBucket: 'todo-3494f.appspot.com',
    iosBundleId: 'com.example.todo',
  );
}
