// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMmbHiZJaJcneMZX4PCJxvamir7UZGNH8',
    appId: '1:853121114268:web:a0171e0b73deca75f58d59',
    messagingSenderId: '853121114268',
    projectId: 'todo-6af75',
    authDomain: 'todo-6af75.firebaseapp.com',
    storageBucket: 'todo-6af75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvKAcaoqnTwHbkx2uXFxaReW1cFVdFKI0',
    appId: '1:853121114268:android:0928fc7b30a85d86f58d59',
    messagingSenderId: '853121114268',
    projectId: 'todo-6af75',
    storageBucket: 'todo-6af75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdVYuet8QeOCPcN2vAzUzeQAfzUmmeMgg',
    appId: '1:853121114268:ios:1a7417c43d7a39aaf58d59',
    messagingSenderId: '853121114268',
    projectId: 'todo-6af75',
    storageBucket: 'todo-6af75.appspot.com',
    iosBundleId: 'com.example.todo',
  );
}
